name: flutter_gherkin
description: A Gherkin / Cucumber parser and test runner for Dart and Flutter
version: 2.0.0
homepage: https://github.com/jonsamwell/flutter_gherkin

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  meta: ">=1.1.6 <2.0.0"
  gherkin:
    git:
      url: git@github.com:olerudyshyn/vos_dart_gherkin.git

dev_dependencies:
  test:
  pedantic: ^1.11.0

flutter:
